### ISSUE TITLE
clarify why an invalid context exists.

### ISSUE THREAD

**Issue by kezabelle** [divio/django-sekizai#11]
If `TEMPLATE_DEBUG` is true, with some additional code complexity, [validate_context](https://github.com/ojii/django-sekizai/blob/bb3992e06339006bea67ebb37daf5992f11a0600/sekizai/templatetags/sekizai_tags.py#L17) could feasibly be more informative about why `{% addtoblock %}` may've failed. Specifically, it could actually do the necessary checks to test whether the context processor is installed, or a `SekizaiContext` is being used, and raise `TemplateSyntaxError` with more definitive messages explaining the nature of the problem.

**Comment by ojii** [comment]
Note: Moved to "Maybe Some Day" milestone, as I'm not sure how to best implement this.

**Comment by DamnedScholar** [comment]
At the very least, `validate_context` should provide a sensible error message. I have been tearing my hair out trying to figure out how `You must enable the 'sekizai.context_processors.sekizai' template context processor or use 'sekizai.context.SekizaiContext' to render your templates.` is the error when `sekizai.context_processors.sekizai` *is* in `TEMPLATE_CONTEXT_PROCESSORS` and I know it works because I have `django-wiki` installed.

**Comment by ojii** [comment]
What would be a "sensible error message"?
