### ISSUE TITLE
Adapt django-sekizai for Django 1.11

### ISSUE THREAD

**Issue by archatas** [divio/django-sekizai#71]
Django sekizai seems to also work on Django 1.11, but I haven't tested all possible cases.
Are there plans to release a new version of django-sekizai anytime soon?

**Comment by archatas** [comment]
Ooops. It looks like this backwards incompatible change has no effect for django-sekizai. I shouldn't report issues at this late time.

**Comment by ojii** [comment]
> Django sekizai seems to also work on Django 1.11,

okay, so where is the problem?

> Are there plans to release a new version of django-sekizai anytime soon?

why? what are the problems that require me to do a release? 

If there are indeed problems, please read this first https://gist.github.com/ojii/d428e7470dc62706f8ee89681bc95208

**Comment by archatas** [comment]
I don't have a concrete case now. I guess just the documentation should rather be updated stating that Django 1.11 is supported.

**Comment by ojii** [comment]
found some bugs with 1.11 and will try to make a release over the holidays later this week.

**Comment by jribbens** [comment]
Any news on this? :-)

**Comment by ojii** [comment]
I did some work on this but it is incredibly low on my list of priorities, so no real news for now.

**Comment by mkoistinen** [comment]
Hi Jonas, anything I can do to help out here? Kinda bummed-out my 1.11 project breaks with your beloved sekizai tags!

**Comment by ojii** [comment]
@mkoistinen since I'm no longer using this project, I'm not too interested in continuing to maintain it. If someone (you?) wants to take over, I'll move the GH project and add them to the pypi project.

**Comment by jribbens** [comment]
divio presumably care about sekizai since django-cms relies on it; maybe they would like to take it over (@vxsx @evildmp)

The fun bit about Django 1.11 is that it explicitly checks that the contexts you pass into the templating system are not, er, Contexts - they must be dictionaries. Going by the Django docs, the value for the 'context' argument was never supposed to be a Context, it was always supposed to be a dictionary. This presumably means that people using the SekizaiContext are going to be out of luck, but I'm guessing most people don't do that, and there's nothing you can do about it anyway.

I have made a pull request #75 which updates the tests so that they now pass on all supported versions of Python and Django up to 3.6 and 1.11.

**Comment by vxsx** [comment]
cc @czpython @finalangel

**Comment by greyhare** [comment]
Should this be closed?
